### ISSUE TITLE
Onchain groups adminWallet

### ISSUE THREAD

**Issue by jdhyun09** [interep-project/docs#2]
<img width="500" alt="스크린샷 2022-03-11 오후 4 29 02" src="https://user-images.githubusercontent.com/48007476/157822064-94b32ab8-ac2f-4cac-95a7-ed8b5a1b95d5.png">
Here's your friendly on-chain group guide. Thanks!<br><br>
But I want to ask, How about adding a Mnemonic deriving path or connecting via privateKey in case using an account by adding more accounts to the Mnemonic wallet(in my case)?

**Comment by cedoor** [comment]
Hi @jdhyun09 , I think this answer could be useful: https://ethereum.stackexchange.com/a/84626. Tell me if it covers your case.

**Comment by jdhyun09** [comment]
Yes, thank you! This covers my case :) But I'm testing by selecting the private key. This gives me the security to hide my main account1. In my personal opinion mnemonic contains too much(Multiple account access by modifying the derivation path.)

This may be my personal question. Any feedback would be helpful!

**Comment by cedoor** [comment]
I think it depends on the context. Mnemonic and private key must always be secret, but if you want to add another security layer and hide the other accounts, using private key could be more secure
